zuul:
  routes:
    test:
      path: /redirect/**
      url: http://google.com
    student:
      path: /student/*
      url: "http://localhost:8083"
    student-service:
      path: student-service/*
      serviceId: student-service
    express-service:
      path: express-service/*
      serviceId: express-vip
    config-server-client:
      path: /config/*
      serviceId: config-server-client

  
spring:    
  application:
    name: zuul

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/